import { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { router } from "expo-router";
import { listInventory } from "../../../src/api/inventory";
import LowStockList from "../../../src/components/inventory/LowStockList";
import { useAuth } from "../../../src/hooks/useAuth";

export default function InventoryScreen() { const { token } = useAuth(); const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(null); const load = async () => { try { setItems(await listInventory(token)); } catch (err) { setError(err.message); } finally { setLoading(false); } }; useEffect(() => { if (token) load(); }, [token]); return <SafeAreaView style={styles.container}><View style={styles.header}><Text style={styles.eyebrow}>COMMERCE</Text><Text style={styles.title}>Inventory</Text><Text style={styles.subtitle}>Available stock and reorder levels</Text></View>{error ? <Text style={styles.error}>{error}</Text> : null}{loading ? <ActivityIndicator style={styles.loader} color="#2563eb" /> : <ScrollView contentContainerStyle={styles.list}>{items.map((item) => <Pressable key={item.id} style={styles.card} onPress={() => router.push(`/(dashboard)/inventory/${item.product_id}`)}><Text style={styles.name}>Product #{item.product_id}</Text><Text style={styles.meta}>{item.available_quantity} available · {item.quantity_reserved} reserved · reorder at {item.reorder_level}</Text></Pressable>)}<Text style={styles.section}>Low stock</Text><LowStockList items={items.filter((item) => item.available_quantity <= item.reorder_level)} /></ScrollView>}</SafeAreaView>; }

const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: "#f1f5f9" }, header: { padding: 20, backgroundColor: "#0f172a" }, eyebrow: { color: "#93c5fd", fontSize: 11, fontWeight: "700", letterSpacing: 1 }, title: { color: "#fff", fontSize: 28, fontWeight: "700", marginTop: 4 }, subtitle: { color: "#cbd5e1", marginTop: 5 }, list: { padding: 16 }, loader: { marginTop: 32 }, card: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#e2e8f0", borderRadius: 10, padding: 14, marginBottom: 10 }, name: { color: "#172033", fontWeight: "700" }, meta: { color: "#64748b", marginTop: 6 }, section: { color: "#172033", fontSize: 18, fontWeight: "800", marginVertical: 14 }, error: { color: "#b91c1c", padding: 16 } });
