from abc import ABC,abstractmethod
class PaymentProvider(ABC):
 @abstractmethod
 def create_intent(self,*,amount:int,currency:str,idempotency_key:str)->dict: ...
 @abstractmethod
 def verify_webhook(self,payload:bytes,signature:str|None)->dict: ...
 @abstractmethod
 def refund(self,provider_payment_id:str,amount:int|None=None)->dict: ...
